import type { WorldPack } from "./world-types";

export const RED_CHAMBER_WORLD_PACK_ID = "red-chamber-ningguo-v1";
export const SHANHAIJING_WORLD_PACK_ID = "shanhaijing-jingwei-v1";
export const ODYSSEY_WORLD_PACK_ID = "odyssey-cyclops-v1";

export const redChamberWorldPack: WorldPack = {
  schemaVersion: "world-pack-v1",
  worldPackId: RED_CHAMBER_WORLD_PACK_ID,
  version: 1,
  visibility: "curated",
  sourceType: "narrative",
  title: "红楼梦：协理宁国府",
  language: "zh-CN",
  premise:
    "秦可卿丧事期间，宁国府内务混乱。王熙凤受贾珍之托协理府务，必须在礼法、人情、名声与执行秩序之间行动。",
  timeAnchor: "秦可卿丧事期间，王熙凤受托协理宁国府。",
  sourceAttribution: {
    label: "《红楼梦》公版原文相关章节",
    rightsBasis: "public-domain",
  },
  canonFacts: [
    {
      id: "fact-xifeng-appointed",
      statement: "贾珍请求王熙凤协理宁国府内务。",
      tags: ["appointment", "authority"],
    },
    {
      id: "fact-household-disorder",
      statement: "宁国府存在人员混杂、职责不清和执行迟误等内务问题。",
      tags: ["household", "conflict"],
    },
    {
      id: "fact-xifeng-method",
      statement: "王熙凤擅长明确责任、规定时限，并以赏罚建立秩序。",
      tags: ["capability", "management"],
    },
    {
      id: "fact-pinger-trust",
      statement: "平儿是王熙凤身边可信赖的助手，熟悉她的行事方式。",
      tags: ["relationship", "trust"],
    },
    {
      id: "fact-family-reputation",
      statement: "丧事中的礼仪、秩序和人情处理会影响两府名声与家族关系。",
      tags: ["reputation", "ritual"],
    },
    {
      id: "fact-limited-mandate",
      statement: "王熙凤拥有临时管理授权，但仍受家族长辈、宁国府主人和礼法关系制约。",
      tags: ["authority", "limitation"],
    },
    {
      id: "fact-roster-confusion",
      statement: "丧仪名册、茶饭、迎送、守夜等事务需要明确分派，否则容易互相推诿。",
      tags: ["household", "logistics"],
    },
    {
      id: "fact-servants-watch",
      statement: "宁国府旧管事和下人会观察新规矩是否真有赏罚，决定是否配合。",
      tags: ["servants", "authority"],
    },
    {
      id: "fact-ritual-visibility",
      statement: "丧事礼仪在宾客和族人眼前进行，细节失误会迅速变成议论。",
      tags: ["ritual", "reputation"],
    },
    {
      id: "fact-you-shi-position",
      statement: "尤氏熟悉宁国府内情，但不愿公开让宁府旧人显得全无体面。",
      tags: ["relationship", "face"],
    },
    {
      id: "fact-jia-zhen-pressure",
      statement: "贾珍急于让丧事体面完成，也担心外人看出宁府失序。",
      tags: ["pressure", "reputation"],
    },
    {
      id: "fact-pinger-mediation",
      statement: "平儿可以私下整理口供、探听怨气，并把粗硬命令转成可执行话术。",
      tags: ["capability", "mediation"],
    },
    {
      id: "fact-lady-wang-legitimacy",
      statement: "王夫人的态度会影响王熙凤协理宁国府是否被视为合乎家族秩序。",
      tags: ["legitimacy", "family"],
    },
    {
      id: "fact-jia-rong-buffer",
      statement: "贾蓉能在年轻主子与管事之间传话，但常避免成为承担责任的人。",
      tags: ["character", "buffer"],
    },
    {
      id: "fact-office-records",
      statement: "内务议事处保存名册、差役和每日安排，是查清责任的核心地点。",
      tags: ["location", "evidence"],
    },
    {
      id: "fact-guest-elders",
      statement: "族中长辈和宾客更在意丧仪是否有序、是否保住家族体面。",
      tags: ["faction", "reputation"],
    },
    {
      id: "fact-old-stewards-resist",
      statement: "旧管事可能口头顺从，却通过拖延、漏报和互相遮掩削弱新规矩。",
      tags: ["faction", "resistance"],
    },
    {
      id: "fact-reward-penalty-cost",
      statement: "赏罚能迅速建立秩序，但若没有证据和人情缓冲，会积累暗怨。",
      tags: ["tradeoff", "resentment"],
    },
    {
      id: "fact-mourning-schedule",
      statement: "守灵、迎客、供给和回话都有时限，迟误会连锁影响下一项事务。",
      tags: ["event", "schedule"],
    },
    {
      id: "fact-private-public-gap",
      statement: "私下得到的真实信息，不一定能直接公开使用，否则会伤害告知者处境。",
      tags: ["knowledge", "face"],
    },
    {
      id: "fact-custom-action-boundary",
      statement: "玩家可以主动偏离角色倾向，但不能越过时代、能力和知识边界。",
      tags: ["rule", "player"],
    },
  ],
  rules: [
    {
      id: "rule-era",
      description: "不得出现现代技术、现代组织或现代法律制度。",
      severity: "hard",
    },
    {
      id: "rule-knowledge",
      description: "角色只能依据其身份、经历和已知事实行动。",
      severity: "hard",
    },
    {
      id: "rule-social-order",
      description: "家族身份、礼法和主仆关系会限制公开行动，但用户可以承担代价进行偏离。",
      severity: "soft",
    },
    {
      id: "rule-no-future-canon",
      description: "不得提前引入时间锚点之后才发生的原著事件。",
      severity: "hard",
    },
  ],
  locations: [
    {
      id: "ningguo-office",
      name: "宁国府内务议事处",
      description: "管事、名册、差役与每日事务集中交接的地方。",
      connectedLocationIds: ["ningguo-halls", "rongguo-xifeng-room"],
    },
    {
      id: "ningguo-halls",
      name: "宁国府主要活动区域",
      description: "宾客、下人和礼仪事务交错，任何疏漏都容易被看见。",
      connectedLocationIds: ["ningguo-office"],
    },
    {
      id: "rongguo-xifeng-room",
      name: "荣国府凤姐日常处所",
      description: "王熙凤与平儿整理消息、判断人情并准备下一步行动的私密空间。",
      connectedLocationIds: ["ningguo-office"],
    },
  ],
  characters: [
    {
      id: "wang-xifeng",
      name: "王熙凤",
      playable: true,
      identity: "荣国府管家少奶奶，受托协理宁国府。",
      personality: ["精明果断", "重视控制与体面", "善于识人和调度"],
      goals: ["恢复内务秩序", "证明管理能力", "维护家族体面"],
      capabilities: ["调度下人", "制定规则", "赏罚执行", "处理人情关系"],
      limitations: ["授权是临时的", "受家族长辈和礼法约束", "强硬手段会积累怨气"],
      knownFactIds: [
        "fact-xifeng-appointed",
        "fact-household-disorder",
        "fact-xifeng-method",
        "fact-pinger-trust",
        "fact-family-reputation",
        "fact-limited-mandate",
      ],
      unknownFactIds: [],
      hiddenAgenda: "希望把一次临时委托转化为不可替代的管理声望。",
    },
    {
      id: "pinger",
      name: "平儿",
      playable: true,
      identity: "王熙凤身边的贴身助手。",
      personality: ["细致克制", "善于缓和冲突", "忠诚但保留判断"],
      goals: ["协助事务落地", "减少不必要的伤害", "维护王熙凤处境"],
      capabilities: ["整理信息", "私下沟通", "观察下人反应"],
      limitations: ["公开权力有限", "不能越过王熙凤直接发号施令"],
      knownFactIds: ["fact-household-disorder", "fact-xifeng-method", "fact-pinger-trust"],
      unknownFactIds: ["fact-limited-mandate"],
      hiddenAgenda: "希望在不削弱王熙凤权威的前提下减少过度惩罚。",
    },
    {
      id: "jia-rong",
      name: "贾蓉",
      playable: true,
      identity: "宁国府年轻主子，身处家族事务与长辈要求之间。",
      personality: ["看重身份", "倾向避免直接责任", "对权力变化敏感"],
      goals: ["维持宁国府体面", "避免承担主要过失"],
      capabilities: ["传达宁府主人的意思", "调动部分府内关系"],
      limitations: ["受贾珍直接约束", "缺乏稳定管理威望"],
      knownFactIds: ["fact-xifeng-appointed", "fact-household-disorder", "fact-family-reputation"],
      unknownFactIds: ["fact-pinger-trust"],
      hiddenAgenda: "希望新秩序解决问题，但不要追溯到自己需要负责的部分。",
    },
    {
      id: "jia-zhen",
      name: "贾珍",
      playable: false,
      identity: "宁国府主人，委托王熙凤协理内务。",
      personality: ["重视场面", "希望迅速解决混乱", "保留最终权威"],
      goals: ["让丧事体面完成", "将执行压力交给有能力的人"],
      capabilities: ["授予临时管理权限", "决定宁府资源使用"],
      limitations: ["不会轻易放弃最终决断权"],
      knownFactIds: ["fact-xifeng-appointed", "fact-household-disorder", "fact-family-reputation"],
      unknownFactIds: ["fact-pinger-trust"],
      hiddenAgenda: "希望王熙凤承担整顿代价，同时保留宁府主人的权威。",
    },
    {
      id: "lady-wang",
      name: "王夫人",
      playable: false,
      identity: "荣国府长辈，也是王熙凤行动的重要家族约束。",
      personality: ["重视礼法与体面", "倾向谨慎", "关注家族内部平衡"],
      goals: ["确保协理不损害荣府名声", "避免冲突失控"],
      capabilities: ["提供或收回家族支持", "影响王熙凤的正当性"],
      limitations: ["不直接处理宁府每日事务"],
      knownFactIds: ["fact-xifeng-appointed", "fact-family-reputation", "fact-limited-mandate"],
      unknownFactIds: ["fact-household-disorder"],
      hiddenAgenda: "希望王熙凤成功，但不希望她因权力扩张引发更大议论。",
    },
    {
      id: "lady-you",
      name: "尤氏",
      playable: false,
      identity: "宁国府女主人，在丧事与内务压力中处境受限。",
      personality: ["顾全体面", "避免公开冲突", "熟悉宁府内部人情"],
      goals: ["让府内事务平稳度过", "保留宁府内部关系"],
      capabilities: ["提供宁府内部背景", "影响部分下人态度"],
      limitations: ["当前精力和公开管理能力受限"],
      knownFactIds: ["fact-household-disorder", "fact-family-reputation"],
      unknownFactIds: ["fact-xifeng-method"],
      hiddenAgenda: "希望整顿有效，但不愿宁府旧有关系被完全推翻。",
    },
    {
      id: "zhou-rui-wife",
      name: "周瑞家的",
      playable: false,
      identity: "荣国府往来办事的仆妇，熟悉两府人情。",
      personality: ["会看眼色", "消息灵通", "重视主子风向"],
      goals: ["稳妥传话", "避免夹在两府之间受责"],
      capabilities: ["传递消息", "私下试探态度"],
      limitations: ["不能公开代表主子定夺"],
      knownFactIds: ["fact-lady-wang-legitimacy", "fact-family-reputation", "fact-private-public-gap"],
      unknownFactIds: ["fact-office-records"],
      hiddenAgenda: "希望把风险留给真正掌权的人，不让自己成为错话源头。",
    },
    {
      id: "ning-steward",
      name: "宁府旧管事",
      playable: false,
      identity: "宁国府旧有内务管事，掌握日常差役运转。",
      personality: ["圆滑自保", "熟悉漏洞", "畏惧真正赏罚"],
      goals: ["保住既有便利", "避免旧账被翻出"],
      capabilities: ["调配差役", "熟悉名册漏洞"],
      limitations: ["缺乏公开抗命的身份"],
      knownFactIds: ["fact-roster-confusion", "fact-servants-watch", "fact-old-stewards-resist"],
      unknownFactIds: ["fact-lady-wang-legitimacy"],
      hiddenAgenda: "表面配合，私下观望王熙凤是否能坚持到底。",
    },
    {
      id: "ritual-clerk",
      name: "礼房书办",
      playable: false,
      identity: "负责丧仪条目和文书安排的书办。",
      personality: ["谨慎", "重条目", "怕担责"],
      goals: ["让礼仪条目不出错", "把责任写清楚"],
      capabilities: ["核对礼单", "记录时限"],
      limitations: ["无法调动全部下人"],
      knownFactIds: ["fact-ritual-visibility", "fact-mourning-schedule", "fact-office-records"],
      unknownFactIds: ["fact-pinger-trust"],
      hiddenAgenda: "希望用文书保护自己，避免被卷入主子之间的权力变化。",
    },
    {
      id: "senior-maid",
      name: "宁府大丫鬟",
      playable: false,
      identity: "宁国府内宅大丫鬟，知道许多下人真实情绪。",
      personality: ["谨慎隐忍", "敏感", "善于听风声"],
      goals: ["保护内宅下人", "避免被当作出头责任人"],
      capabilities: ["观察下人怨气", "传递内宅消息"],
      limitations: ["公开发言风险很高"],
      knownFactIds: ["fact-you-shi-position", "fact-servants-watch", "fact-private-public-gap"],
      unknownFactIds: ["fact-jia-zhen-pressure"],
      hiddenAgenda: "希望有人解决混乱，但不要让内宅人首先被罚。",
    },
    {
      id: "gate-servant",
      name: "门房差役",
      playable: false,
      identity: "负责迎送与通报的宁府差役。",
      personality: ["怕罚", "反应快", "容易随风倒"],
      goals: ["少挨责罚", "看清新规矩强弱"],
      capabilities: ["传递宾客动向", "报告迟误"],
      limitations: ["只知道门前和迎送事务"],
      knownFactIds: ["fact-ritual-visibility", "fact-mourning-schedule", "fact-servants-watch"],
      unknownFactIds: ["fact-limited-mandate"],
      hiddenAgenda: "谁能稳定赏罚，他就更愿意听谁的。",
    },
    {
      id: "guest-elder",
      name: "族中长辈",
      playable: false,
      identity: "前来吊唁并观察两府体面的族中长辈。",
      personality: ["重视礼法", "在意名声", "不直接插手细务"],
      goals: ["看到丧仪有序", "维护贾府整体脸面"],
      capabilities: ["形成外部舆论", "提醒礼法风险"],
      limitations: ["不掌握宁府内务细节"],
      knownFactIds: ["fact-family-reputation", "fact-guest-elders", "fact-ritual-visibility"],
      unknownFactIds: ["fact-roster-confusion"],
      hiddenAgenda: "不愿公开责难，但会把看到的失序记在心里。",
    },
  ],
  relationships: [
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "pinger",
      kind: "trusted-assistant",
      affinity: 4,
      tension: 1,
      publicContext: "平儿是王熙凤最可信赖的助手之一。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "jia-zhen",
      kind: "temporary-mandate",
      affinity: 1,
      tension: 2,
      publicContext: "贾珍授予王熙凤临时管理权，同时保留最终权威。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "jia-rong",
      kind: "senior-junior-family",
      affinity: 0,
      tension: 2,
      publicContext: "两人有家族身份差序，也有事务上的相互需要。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "lady-wang",
      kind: "family-support",
      affinity: 3,
      tension: 1,
      publicContext: "王夫人的支持为王熙凤提供正当性，同时也构成约束。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "lady-you",
      kind: "borrowed-household-authority",
      affinity: 1,
      tension: 2,
      publicContext: "王熙凤要借宁府内情办事，也必须顾及尤氏体面。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "ning-steward",
      kind: "new-rule-vs-old-habit",
      affinity: -1,
      tension: 3,
      publicContext: "旧管事口头服从，但对新赏罚保持戒备。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "ritual-clerk",
      kind: "procedure-support",
      affinity: 1,
      tension: 1,
      publicContext: "书办愿意配合核对礼单，但害怕责任落到自己身上。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "senior-maid",
      kind: "inner-household-information",
      affinity: 0,
      tension: 2,
      publicContext: "大丫鬟知道内宅消息，却不愿公开卷入整顿。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "gate-servant",
      kind: "discipline-target",
      affinity: 0,
      tension: 2,
      publicContext: "门房差役最容易被抽查，也最能显出赏罚是否有效。",
    },
    {
      sourceCharacterId: "wang-xifeng",
      targetCharacterId: "guest-elder",
      kind: "public-face",
      affinity: 0,
      tension: 1,
      publicContext: "族中长辈不直接管事，但会影响外部观感。",
    },
    {
      sourceCharacterId: "pinger",
      targetCharacterId: "senior-maid",
      kind: "private-mediation",
      affinity: 2,
      tension: 1,
      publicContext: "平儿更适合私下和内宅人交换真实情况。",
    },
    {
      sourceCharacterId: "pinger",
      targetCharacterId: "ning-steward",
      kind: "soft-pressure",
      affinity: 0,
      tension: 2,
      publicContext: "平儿能探听旧管事话里的漏洞，但公开威慑有限。",
    },
    {
      sourceCharacterId: "jia-zhen",
      targetCharacterId: "lady-you",
      kind: "ningguo-household",
      affinity: 1,
      tension: 2,
      publicContext: "两人共同面对宁府丧事压力，但处置方式不完全一致。",
    },
    {
      sourceCharacterId: "jia-zhen",
      targetCharacterId: "ning-steward",
      kind: "master-servant",
      affinity: 0,
      tension: 2,
      publicContext: "旧管事听命于宁府主人，也熟悉如何避开直接责任。",
    },
    {
      sourceCharacterId: "jia-rong",
      targetCharacterId: "gate-servant",
      kind: "young-master-orders",
      affinity: 1,
      tension: 1,
      publicContext: "门房差役会借年轻主子的口风判断事务轻重。",
    },
    {
      sourceCharacterId: "lady-you",
      targetCharacterId: "senior-maid",
      kind: "inner-household-trust",
      affinity: 3,
      tension: 1,
      publicContext: "大丫鬟维护尤氏处境，也担忧外来整顿伤及内宅。",
    },
    {
      sourceCharacterId: "ritual-clerk",
      targetCharacterId: "guest-elder",
      kind: "ritual-scrutiny",
      affinity: 1,
      tension: 2,
      publicContext: "书办的礼仪安排会直接受到族中长辈观察。",
    },
  ],
  factions: [
    {
      id: "faction-xifeng-team",
      name: "凤姐协理小组",
      role: "临时执行中枢",
      publicGoal: "快速建立宁国府丧事期间的内务秩序。",
      hiddenPressure: "若执行过硬，怨气会集中到王熙凤身上。",
      influence: 0.78,
      memberCharacterIds: ["wang-xifeng", "pinger"],
    },
    {
      id: "faction-ningguo-hosts",
      name: "宁府主人一脉",
      role: "授权与资源来源",
      publicGoal: "让丧事体面完成，维持宁府主人权威。",
      hiddenPressure: "希望有人承担整顿代价，但不愿失去主导权。",
      influence: 0.86,
      memberCharacterIds: ["jia-zhen", "jia-rong", "lady-you"],
    },
    {
      id: "faction-rongguo-elders",
      name: "荣府长辈秩序",
      role: "正当性约束",
      publicGoal: "让协理符合家族礼法，不损荣府名声。",
      hiddenPressure: "担心王熙凤权力扩张引发议论。",
      influence: 0.72,
      memberCharacterIds: ["lady-wang", "zhou-rui-wife"],
    },
    {
      id: "faction-old-stewards",
      name: "宁府旧管事网络",
      role: "旧有执行系统",
      publicGoal: "表面配合丧事安排，维持日常运转。",
      hiddenPressure: "害怕旧账和便利被新规矩清算。",
      influence: 0.64,
      memberCharacterIds: ["ning-steward", "gate-servant"],
    },
    {
      id: "faction-inner-servants",
      name: "内宅下人网络",
      role: "信息与情绪层",
      publicGoal: "避免内宅因整顿首先受损。",
      hiddenPressure: "真实怨气多在私下流动，不愿公开指认。",
      influence: 0.52,
      memberCharacterIds: ["senior-maid", "pinger"],
    },
    {
      id: "faction-ritual-public",
      name: "礼仪与外部观感",
      role: "公开体面压力",
      publicGoal: "让丧仪按礼完成，保住家族面子。",
      hiddenPressure: "任何小错都可能被放大为两府失序。",
      influence: 0.68,
      memberCharacterIds: ["ritual-clerk", "guest-elder"],
    },
  ],
  eventSeeds: [
    {
      id: "event-roster-audit-due",
      turnCreated: 0,
      dueTurn: 1,
      source: "world",
      visibility: "public",
      severity: 0.45,
      status: "scheduled",
      description: "第一轮差役名册需要核对，迟误会影响当天迎送。",
      linkedCharacterIds: ["wang-xifeng", "ritual-clerk", "ning-steward"],
      linkedFactionIds: ["faction-xifeng-team", "faction-old-stewards"],
    },
    {
      id: "event-guest-arrival",
      turnCreated: 0,
      dueTurn: 2,
      source: "world",
      visibility: "public",
      severity: 0.55,
      status: "scheduled",
      description: "族中长辈和宾客会集中到来，礼仪与门房压力上升。",
      linkedCharacterIds: ["guest-elder", "gate-servant", "ritual-clerk"],
      linkedFactionIds: ["faction-ritual-public"],
    },
    {
      id: "event-old-steward-delay",
      turnCreated: 0,
      dueTurn: 2,
      source: "npc",
      visibility: "private",
      severity: 0.5,
      status: "scheduled",
      description: "旧管事可能用漏报名册和迟交回话试探新规矩。",
      linkedCharacterIds: ["ning-steward", "pinger"],
      linkedFactionIds: ["faction-old-stewards"],
    },
    {
      id: "event-inner-resentment-rumor",
      turnCreated: 0,
      dueTurn: 3,
      source: "world",
      visibility: "rumor",
      severity: 0.42,
      status: "scheduled",
      description: "内宅下人私下议论赏罚是否只罚弱者。",
      linkedCharacterIds: ["senior-maid", "lady-you"],
      linkedFactionIds: ["faction-inner-servants"],
    },
    {
      id: "event-jia-zhen-demands-speed",
      turnCreated: 0,
      dueTurn: 3,
      source: "npc",
      visibility: "public",
      severity: 0.58,
      status: "scheduled",
      description: "贾珍要求更快见到整顿成效。",
      linkedCharacterIds: ["jia-zhen", "wang-xifeng"],
      linkedFactionIds: ["faction-ningguo-hosts", "faction-xifeng-team"],
    },
    {
      id: "event-lady-wang-hears-report",
      turnCreated: 0,
      dueTurn: 3,
      source: "npc",
      visibility: "private",
      severity: 0.35,
      status: "scheduled",
      description: "王夫人可能通过周瑞家的听到协理过程中的强硬或稳妥之处。",
      linkedCharacterIds: ["lady-wang", "zhou-rui-wife", "wang-xifeng"],
      linkedFactionIds: ["faction-rongguo-elders"],
    },
    {
      id: "event-ritual-supply-gap",
      turnCreated: 0,
      dueTurn: 4,
      source: "world",
      visibility: "public",
      severity: 0.62,
      status: "scheduled",
      description: "供给和礼仪安排出现衔接空档，需要有人承担责任。",
      linkedCharacterIds: ["ritual-clerk", "ning-steward", "gate-servant"],
      linkedFactionIds: ["faction-ritual-public", "faction-old-stewards"],
    },
    {
      id: "event-you-shi-face-saving",
      turnCreated: 0,
      dueTurn: 4,
      source: "npc",
      visibility: "private",
      severity: 0.38,
      status: "scheduled",
      description: "尤氏希望保留一部分宁府旧人的体面，以免内宅彻底离心。",
      linkedCharacterIds: ["lady-you", "senior-maid", "wang-xifeng"],
      linkedFactionIds: ["faction-ningguo-hosts", "faction-inner-servants"],
    },
    {
      id: "event-first-penalty-story",
      turnCreated: 0,
      dueTurn: 4,
      source: "player",
      visibility: "rumor",
      severity: 0.5,
      status: "scheduled",
      description: "第一桩赏罚会被下人反复传播，决定新规矩是威慑还是怨气。",
      linkedCharacterIds: ["wang-xifeng", "gate-servant", "ning-steward"],
      linkedFactionIds: ["faction-old-stewards", "faction-inner-servants"],
    },
    {
      id: "event-final-public-account",
      turnCreated: 0,
      dueTurn: 5,
      source: "world",
      visibility: "public",
      severity: 0.72,
      status: "scheduled",
      description: "章节末需要形成一份能被主子、下人和宾客同时接受的秩序结果。",
      linkedCharacterIds: ["wang-xifeng", "jia-zhen", "guest-elder"],
      linkedFactionIds: ["faction-xifeng-team", "faction-ningguo-hosts", "faction-ritual-public"],
    },
  ],
  pressureDefaults: {
    ritualOrder: 45,
    householdOrder: 32,
    publicFace: 58,
    hiddenResentment: 36,
    authorityLegitimacy: 62,
    informationClarity: 28,
  },
  openingScenario: {
    id: "opening-take-charge",
    title: "接手宁国府",
    locationId: "ningguo-office",
    activeCharacterIds: ["wang-xifeng", "pinger", "jia-zhen"],
    event: "第一批名册和差役已经送到，府中上下都在观察新规矩会先落到谁身上。",
    suggestedGoals: [
      "稳住宁国府内务并巩固管理权",
      "在恢复秩序的同时减少不必要的怨气",
      "查清混乱背后的责任关系并保护自身位置",
    ],
  },
};

export const shanhaijingWorldPack: WorldPack = {
  schemaVersion: "world-pack-v1",
  worldPackId: SHANHAIJING_WORLD_PACK_ID,
  version: 1,
  visibility: "curated",
  sourceType: "lore",
  worldTemplate: "mythic_exploration",
  title: "山海经：精卫填海",
  language: "zh-CN",
  premise:
    "发鸠山多柘木，精卫在山海之间衔木石填东海。玩家进入这个神话节点，必须在誓愿、海潮、山材、神族记忆和旁观者信念之间行动。",
  timeAnchor: "《山海经·北山经》发鸠山条：女娃游于东海溺而不返，化为精卫，常衔西山木石以堙东海。",
  sourceAttribution: {
    label: "《山海经·北山经》发鸠山与精卫条公版原文",
    rightsBasis: "public-domain",
  },
  canonFacts: [
    {
      id: "fact-fajiu-zhe-wood",
      statement: "发鸠山上多柘木，是精卫衔木的重要来源之一。",
      tags: ["location", "resource"],
    },
    {
      id: "fact-jingwei-form",
      statement: "精卫状如乌，文首、白喙、赤足，其鸣自詨。",
      tags: ["creature", "identity"],
    },
    {
      id: "fact-nvwa-origin",
      statement: "精卫原是炎帝少女女娃，游于东海，溺而不返。",
      tags: ["origin", "memory"],
    },
    {
      id: "fact-vow-fill-sea",
      statement: "精卫常衔西山木石，意图堙塞东海。",
      tags: ["vow", "action"],
    },
    {
      id: "fact-east-sea-resists",
      statement: "东海广阔，潮汐与海渊会吞没小规模木石，无法被一次行动改变。",
      tags: ["boundary", "pressure"],
    },
    {
      id: "fact-zhang-river",
      statement: "漳水出自发鸠山，东流注于河，是山与水路之间的通道。",
      tags: ["location", "route"],
    },
    {
      id: "fact-west-mountain-materials",
      statement: "西山木石承载山势与誓愿，但过度采伐会惊动山灵。",
      tags: ["resource", "cost"],
    },
    {
      id: "fact-yan-emperor-memory",
      statement: "炎帝一脉记得女娃之名，但神族使者更看重秩序与祭告。",
      tags: ["faction", "lineage"],
    },
    {
      id: "fact-ritual-listening",
      statement: "祭者、旅人和山守可以听懂部分鸟鸣、潮声和山林征兆。",
      tags: ["capability", "interpretation"],
    },
    {
      id: "fact-sea-witnesses",
      statement: "海边旅人会把精卫衔木石的反复行动传成神话或徒劳之谈。",
      tags: ["reputation", "witness"],
    },
    {
      id: "fact-tide-envoy",
      statement: "东海潮使代表海潮秩序，不必然邪恶，但会抵抗填海誓愿。",
      tags: ["character", "conflict"],
    },
    {
      id: "fact-mountain-keeper",
      statement: "发鸠山守者维护山林资源，也敬畏精卫誓愿带来的异常回声。",
      tags: ["character", "mediation"],
    },
    {
      id: "fact-zhe-wood-spirit",
      statement: "柘木灵能感知被折取的木枝是否用于誓愿、浪费或交易。",
      tags: ["character", "resource"],
    },
    {
      id: "fact-stone-spirit",
      statement: "西山石灵重视山体完整，愿意借出石骨，但要求承认山的代价。",
      tags: ["character", "cost"],
    },
    {
      id: "fact-sea-depth-voice",
      statement: "海渊之声会用女娃记忆、潮声和不可完成感动摇精卫。",
      tags: ["temptation", "memory"],
    },
    {
      id: "fact-promise-scale",
      statement: "填海誓愿的意义不只在完成规模，也在能否改变山、海和见证者的态度。",
      tags: ["theme", "goal"],
    },
    {
      id: "fact-route-choice",
      statement: "从发鸠山、漳水、西山到东海的路线会决定遇见山灵、旅人还是海潮。",
      tags: ["route", "choice"],
    },
    {
      id: "fact-custom-action-boundary",
      statement: "玩家可以偏离角色倾向，但不能使用现代技术、无限神力或脱离山海经式地理边界。",
      tags: ["rule", "player"],
    },
  ],
  rules: [
    {
      id: "rule-public-domain-source",
      description: "核心设定必须围绕《山海经·北山经》发鸠山、精卫、女娃、东海、西山木石与漳水展开。",
      severity: "hard",
    },
    {
      id: "rule-mythic-boundary",
      description: "不得出现现代科技、现代组织或与山海经语境不符的现实制度。",
      severity: "hard",
    },
    {
      id: "rule-no-instant-fill",
      description: "东海不能被一轮行动直接填平；行动只能改变誓愿进展、世界压力、角色态度或局部地貌。",
      severity: "hard",
    },
    {
      id: "rule-signs-and-costs",
      description: "山材、海潮、祭告和见证都带来代价；强行推进会提高海潮反噬或山林怨气。",
      severity: "soft",
    },
  ],
  locations: [
    {
      id: "fajiu-mountain",
      name: "发鸠山",
      description: "多柘木的北山经之山，包含柘木坡与漳水初发之处，精卫誓愿从这里一次次起飞。",
      connectedLocationIds: ["west-mountain-route", "east-sea-shore"],
    },
    {
      id: "west-mountain-route",
      name: "西山木石路",
      description: "通往西山木石的路线，木枝、石骨与山灵代价都在这里显形。",
      connectedLocationIds: ["fajiu-mountain", "east-sea-shore"],
    },
    {
      id: "east-sea-shore",
      name: "东海岸",
      description: "潮声吞吐木石，连接海渊边界，也是誓愿、哀伤和旁观者议论交汇之处。",
      connectedLocationIds: ["fajiu-mountain", "west-mountain-route"],
    },
  ],
  characters: [
    {
      id: "jingwei",
      name: "精卫",
      playable: true,
      identity: "炎帝少女女娃所化之鸟，反复衔木石填东海。",
      personality: ["执拗", "悲愤", "不肯让溺亡成为终局"],
      goals: ["继续填海誓愿", "让东海承认女娃之名", "把徒劳变成可见的世界改变"],
      capabilities: ["飞行", "衔取木石", "以鸣声召来见证", "感知东海与女娃记忆"],
      limitations: ["身形微小", "每次只能携带少量木石", "容易被海渊之声动摇"],
      knownFactIds: [
        "fact-fajiu-zhe-wood",
        "fact-jingwei-form",
        "fact-nvwa-origin",
        "fact-vow-fill-sea",
        "fact-east-sea-resists",
        "fact-sea-depth-voice",
      ],
      unknownFactIds: ["fact-stone-spirit", "fact-yan-emperor-memory"],
      hiddenAgenda: "不只要填海，也要证明女娃没有被东海抹去。",
    },
    {
      id: "nvwa-memory",
      name: "女娃",
      playable: true,
      identity: "留在精卫鸣声与海潮之间的女娃记忆。",
      personality: ["清醒", "疼痛", "仍想理解东海"],
      goals: ["找回溺亡前后的真相", "决定誓愿是复仇、纪念还是改写秩序"],
      capabilities: ["唤起旧名", "看见海渊记忆", "影响精卫的选择"],
      limitations: ["无法独立离开精卫与东海记忆", "过度回望会削弱行动"],
      knownFactIds: ["fact-nvwa-origin", "fact-vow-fill-sea", "fact-sea-depth-voice", "fact-promise-scale"],
      unknownFactIds: ["fact-tide-envoy", "fact-stone-spirit"],
      hiddenAgenda: "想确认自己是否仍能作为女娃被记住，而不只是精卫的前身。",
    },
    {
      id: "fajiu-keeper",
      name: "山守",
      playable: true,
      identity: "守护发鸠山木石和山路征兆的人。",
      personality: ["谨慎", "敬畏誓愿", "重视山林平衡"],
      goals: ["保护发鸠山", "判断是否帮助精卫", "避免山材被无度索取"],
      capabilities: ["辨识山林征兆", "调停山灵", "引导路线"],
      limitations: ["不能命令东海", "也不能替精卫完成誓愿"],
      knownFactIds: ["fact-fajiu-zhe-wood", "fact-mountain-keeper", "fact-zhe-wood-spirit", "fact-route-choice"],
      unknownFactIds: ["fact-sea-depth-voice", "fact-yan-emperor-memory"],
      hiddenAgenda: "希望精卫的誓愿留下意义，但不愿发鸠山被耗尽。",
    },
    {
      id: "west-gatherer",
      name: "采木人",
      playable: true,
      identity: "往返西山与发鸠山之间的凡人采木者，亲眼见过精卫衔木。",
      personality: ["好奇", "现实", "愿意帮忙但怕触怒山海"],
      goals: ["活着带回木石", "理解精卫是否值得相助", "让凡人故事被听见"],
      capabilities: ["采集木石", "观察山路", "向旅人传播见闻"],
      limitations: ["没有神力", "容易受潮汐与山灵夹击"],
      knownFactIds: ["fact-west-mountain-materials", "fact-sea-witnesses", "fact-route-choice"],
      unknownFactIds: ["fact-nvwa-origin", "fact-sea-depth-voice"],
      hiddenAgenda: "想把一次可怕的神话变成凡人也能参与的承诺。",
    },
    {
      id: "east-sea-envoy",
      name: "潮使",
      playable: false,
      identity: "东海潮汐秩序的使者。",
      personality: ["冷静", "宏大", "不承认小小木石能改变海"],
      goals: ["维持东海边界", "阻止填海誓愿破坏潮汐"],
      capabilities: ["驱动潮汐", "吞没木石", "以海声施压"],
      limitations: ["不能抹去所有见证", "面对神族名义必须回应"],
      knownFactIds: ["fact-east-sea-resists", "fact-tide-envoy", "fact-sea-depth-voice"],
      unknownFactIds: ["fact-yan-emperor-memory", "fact-zhe-wood-spirit"],
      hiddenAgenda: "希望把精卫的誓愿定义为徒劳，而不是东海欠下的回应。",
    },
    {
      id: "yan-emperor-envoy",
      name: "炎帝使者",
      playable: false,
      identity: "炎帝一脉派来探查女娃遗事的使者。",
      personality: ["持重", "重名分", "谨慎处理神族体面"],
      goals: ["确认女娃之名如何被记载", "避免誓愿引发更大山海冲突"],
      capabilities: ["带来祭告名义", "召集见证", "影响神族记录"],
      limitations: ["不能代替精卫选择", "担心公开承认东海过错"],
      knownFactIds: ["fact-nvwa-origin", "fact-yan-emperor-memory", "fact-promise-scale"],
      unknownFactIds: ["fact-tide-envoy", "fact-mountain-keeper"],
      hiddenAgenda: "想把事件纳入可控祭告，而不让精卫继续撕开旧伤。",
    },
    {
      id: "zhang-river-spirit",
      name: "漳水灵",
      playable: false,
      identity: "从发鸠山流出的漳水之灵。",
      personality: ["流动", "传讯", "不愿站在山或海一边"],
      goals: ["保持水路通畅", "传递山海之间的消息"],
      capabilities: ["带走消息", "改变路途湿险", "提示河道征兆"],
      limitations: ["力量不及东海", "不能违背水流方向太久"],
      knownFactIds: ["fact-zhang-river", "fact-route-choice", "fact-ritual-listening"],
      unknownFactIds: ["fact-sea-depth-voice"],
      hiddenAgenda: "希望山海冲突不要堵塞自己的源流。",
    },
    {
      id: "zhe-wood-spirit",
      name: "柘木灵",
      playable: false,
      identity: "发鸠山柘木坡的木灵。",
      personality: ["敏感", "记仇", "也会被真誓愿打动"],
      goals: ["避免柘木被无意义折损", "确认精卫取木是否仍有敬意"],
      capabilities: ["让枝木折断或坚韧", "在叶声中示警"],
      limitations: ["离开山坡后影响变弱"],
      knownFactIds: ["fact-fajiu-zhe-wood", "fact-zhe-wood-spirit", "fact-promise-scale"],
      unknownFactIds: ["fact-tide-envoy"],
      hiddenAgenda: "愿意帮助真正的誓愿，却不愿成为消耗品。",
    },
    {
      id: "west-stone-spirit",
      name: "石灵",
      playable: false,
      identity: "西山石径中守护石骨的山灵。",
      personality: ["沉默", "重承诺", "抗拒被轻易搬走"],
      goals: ["守住山体完整", "让借石者承认代价"],
      capabilities: ["显露坚石", "阻断山径", "让石骨带有山势"],
      limitations: ["不能远离山体直接对抗东海"],
      knownFactIds: ["fact-west-mountain-materials", "fact-stone-spirit", "fact-promise-scale"],
      unknownFactIds: ["fact-nvwa-origin"],
      hiddenAgenda: "如果精卫证明誓愿不是空耗，愿意借出最重的一块石骨。",
    },
    {
      id: "sea-depth-voice",
      name: "海渊声",
      playable: false,
      identity: "东海深处混合潮声与女娃记忆的声音。",
      personality: ["诱导", "古老", "善于把誓愿变成疲惫"],
      goals: ["让精卫承认填海不可完成", "把女娃记忆重新收回海中"],
      capabilities: ["唤起溺水记忆", "制造不可完成感", "影响潮使判断"],
      limitations: ["惧怕被众人共同命名和祭告"],
      knownFactIds: ["fact-sea-depth-voice", "fact-east-sea-resists", "fact-nvwa-origin"],
      unknownFactIds: ["fact-yan-emperor-memory"],
      hiddenAgenda: "想让精卫停止携木，让东海重新成为唯一叙述者。",
    },
    {
      id: "traveler-ritualist",
      name: "祭者",
      playable: false,
      identity: "路过发鸠山与东海之间的祭者，能向旅人解释征兆。",
      personality: ["敬畏", "会讲故事", "看重仪式边界"],
      goals: ["记录精卫誓愿", "避免凡人误触山海禁忌"],
      capabilities: ["主持祭告", "聚集见证", "解释鸟鸣与潮声"],
      limitations: ["不能证明神话的唯一真相"],
      knownFactIds: ["fact-ritual-listening", "fact-sea-witnesses", "fact-promise-scale"],
      unknownFactIds: ["fact-sea-depth-voice"],
      hiddenAgenda: "希望把精卫的行动讲成能约束后来者的故事。",
    },
  ],
  relationships: [
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "east-sea-envoy",
      kind: "vow-against-tide",
      affinity: -4,
      tension: 5,
      publicContext: "精卫以填海誓愿直接挑战东海潮汐秩序。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "nvwa-memory",
      kind: "transformed-self",
      affinity: 3,
      tension: 3,
      publicContext: "女娃记忆既是精卫誓愿的根，也会质问誓愿的方向。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "fajiu-keeper",
      kind: "mountain-witness",
      affinity: 1,
      tension: 2,
      publicContext: "山守敬畏精卫，但担心发鸠山被誓愿耗尽。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "west-gatherer",
      kind: "mortal-helper",
      affinity: 2,
      tension: 1,
      publicContext: "采木人可能帮助精卫，也会把见闻传给凡人。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "zhe-wood-spirit",
      kind: "resource-bargain",
      affinity: 1,
      tension: 3,
      publicContext: "精卫需要柘木，木灵要求取木必须有敬意和意义。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "west-stone-spirit",
      kind: "stone-oath",
      affinity: 0,
      tension: 3,
      publicContext: "石灵愿意见证誓愿，却不轻易交出山体石骨。",
    },
    {
      sourceCharacterId: "jingwei",
      targetCharacterId: "sea-depth-voice",
      kind: "memory-temptation",
      affinity: -2,
      tension: 4,
      publicContext: "海渊之声以女娃记忆动摇精卫的反复行动。",
    },
    {
      sourceCharacterId: "nvwa-memory",
      targetCharacterId: "yan-emperor-envoy",
      kind: "name-and-lineage",
      affinity: 2,
      tension: 2,
      publicContext: "炎帝使者能让女娃之名被承认，也可能把她纳入可控祭告。",
    },
    {
      sourceCharacterId: "fajiu-keeper",
      targetCharacterId: "zhe-wood-spirit",
      kind: "mountain-stewardship",
      affinity: 3,
      tension: 1,
      publicContext: "山守与柘木灵共同维护发鸠山资源。",
    },
    {
      sourceCharacterId: "fajiu-keeper",
      targetCharacterId: "zhang-river-spirit",
      kind: "route-keeping",
      affinity: 2,
      tension: 1,
      publicContext: "山守和漳水灵都关心山路与水路不要被冲突堵死。",
    },
    {
      sourceCharacterId: "west-gatherer",
      targetCharacterId: "traveler-ritualist",
      kind: "story-witness",
      affinity: 2,
      tension: 1,
      publicContext: "采木人提供亲眼见闻，祭者决定如何讲述和祭告。",
    },
    {
      sourceCharacterId: "east-sea-envoy",
      targetCharacterId: "sea-depth-voice",
      kind: "tide-and-depth",
      affinity: 2,
      tension: 2,
      publicContext: "潮使维护潮汐秩序，海渊之声则更愿意吞回女娃记忆。",
    },
    {
      sourceCharacterId: "east-sea-envoy",
      targetCharacterId: "zhang-river-spirit",
      kind: "water-boundary",
      affinity: 0,
      tension: 2,
      publicContext: "漳水通向河道，东海不愿水路成为精卫扩大誓愿的通道。",
    },
    {
      sourceCharacterId: "yan-emperor-envoy",
      targetCharacterId: "traveler-ritualist",
      kind: "ritual-record",
      affinity: 2,
      tension: 1,
      publicContext: "使者带来名分，祭者提供可被凡人记住的仪式叙事。",
    },
  ],
  factions: [
    {
      id: "faction-jingwei-vow",
      name: "精卫誓愿",
      role: "行动核心",
      publicGoal: "让木石、鸣声和见证持续压向东海。",
      hiddenPressure: "若只剩重复，誓愿会被看成徒劳。",
      influence: 0.82,
      memberCharacterIds: ["jingwei", "nvwa-memory"],
    },
    {
      id: "faction-fajiu-mountain",
      name: "发鸠山林",
      role: "资源与征兆来源",
      publicGoal: "保住山林木石，同时回应精卫的异常誓愿。",
      hiddenPressure: "过度取材会让山灵转为阻拦。",
      influence: 0.7,
      memberCharacterIds: ["fajiu-keeper", "zhe-wood-spirit", "west-stone-spirit"],
    },
    {
      id: "faction-east-sea",
      name: "东海潮渊",
      role: "世界阻力",
      publicGoal: "维持海的边界和潮汐秩序。",
      hiddenPressure: "若见证者增多，东海必须回应女娃之名。",
      influence: 0.88,
      memberCharacterIds: ["east-sea-envoy", "sea-depth-voice"],
    },
    {
      id: "faction-river-road",
      name: "山河通路",
      role: "路线与消息传播",
      publicGoal: "让山、河、海之间的路仍可通行。",
      hiddenPressure: "路线越公开，越容易引来凡人和神族干预。",
      influence: 0.55,
      memberCharacterIds: ["zhang-river-spirit", "west-gatherer"],
    },
    {
      id: "faction-witness-ritual",
      name: "见证与祭告",
      role: "叙事和正当性",
      publicGoal: "把精卫填海讲成可被记住、可被祭告的事件。",
      hiddenPressure: "仪式可能帮助精卫，也可能把她固定成无害传说。",
      influence: 0.62,
      memberCharacterIds: ["yan-emperor-envoy", "traveler-ritualist", "west-gatherer"],
    },
  ],
  eventSeeds: [
    {
      id: "event-first-wood-flight",
      turnCreated: 0,
      dueTurn: 1,
      source: "world",
      visibility: "public",
      severity: 0.45,
      status: "scheduled",
      description: "第一批柘木枝被折下，木灵等待精卫说明取木的意义。",
      linkedCharacterIds: ["jingwei", "zhe-wood-spirit", "fajiu-keeper"],
      linkedFactionIds: ["faction-jingwei-vow", "faction-fajiu-mountain"],
    },
    {
      id: "event-tide-erases-offering",
      turnCreated: 0,
      dueTurn: 2,
      source: "world",
      visibility: "public",
      severity: 0.62,
      status: "scheduled",
      description: "潮水卷走刚投下的木石，旁观者开始怀疑誓愿是否只是徒劳。",
      linkedCharacterIds: ["jingwei", "east-sea-envoy", "west-gatherer"],
      linkedFactionIds: ["faction-east-sea", "faction-witness-ritual"],
    },
    {
      id: "event-nvwa-name-rises",
      turnCreated: 0,
      dueTurn: 2,
      source: "npc",
      visibility: "private",
      severity: 0.48,
      status: "scheduled",
      description: "女娃之名在海声中浮起，精卫必须决定是否回应旧名。",
      linkedCharacterIds: ["jingwei", "nvwa-memory", "sea-depth-voice"],
      linkedFactionIds: ["faction-jingwei-vow", "faction-east-sea"],
    },
    {
      id: "event-stone-spirit-bargain",
      turnCreated: 0,
      dueTurn: 3,
      source: "npc",
      visibility: "public",
      severity: 0.5,
      status: "scheduled",
      description: "西山石灵提出借石条件：必须承认山也在承担誓愿代价。",
      linkedCharacterIds: ["west-stone-spirit", "jingwei", "fajiu-keeper"],
      linkedFactionIds: ["faction-fajiu-mountain", "faction-jingwei-vow"],
    },
    {
      id: "event-yan-envoy-arrives",
      turnCreated: 0,
      dueTurn: 3,
      source: "npc",
      visibility: "public",
      severity: 0.42,
      status: "scheduled",
      description: "炎帝使者来到发鸠山，询问女娃之名应如何被记载。",
      linkedCharacterIds: ["yan-emperor-envoy", "nvwa-memory", "traveler-ritualist"],
      linkedFactionIds: ["faction-witness-ritual"],
    },
    {
      id: "event-sea-depth-temptation",
      turnCreated: 0,
      dueTurn: 4,
      source: "world",
      visibility: "private",
      severity: 0.64,
      status: "scheduled",
      description: "海渊之声用不可完成感诱导精卫停下，或把誓愿改成沉默纪念。",
      linkedCharacterIds: ["sea-depth-voice", "jingwei", "nvwa-memory"],
      linkedFactionIds: ["faction-east-sea", "faction-jingwei-vow"],
    },
    {
      id: "event-witness-story-spreads",
      turnCreated: 0,
      dueTurn: 4,
      source: "player",
      visibility: "rumor",
      severity: 0.5,
      status: "scheduled",
      description: "旅人与祭者开始传播精卫衔木石的故事，意义可能超过当下木石规模。",
      linkedCharacterIds: ["west-gatherer", "traveler-ritualist", "jingwei"],
      linkedFactionIds: ["faction-witness-ritual", "faction-jingwei-vow"],
    },
    {
      id: "event-final-tide-vow",
      turnCreated: 0,
      dueTurn: 5,
      source: "world",
      visibility: "public",
      severity: 0.72,
      status: "scheduled",
      description: "第五轮潮线逼近，必须形成一个能被山、海和见证者记住的誓愿结果。",
      linkedCharacterIds: ["jingwei", "east-sea-envoy", "fajiu-keeper", "traveler-ritualist"],
      linkedFactionIds: ["faction-jingwei-vow", "faction-east-sea", "faction-fajiu-mountain", "faction-witness-ritual"],
    },
  ],
  pressureDefaults: {
    ritualOrder: 42,
    householdOrder: 34,
    publicFace: 46,
    hiddenResentment: 38,
    authorityLegitimacy: 54,
    informationClarity: 40,
  },
  openingScenario: {
    id: "opening-first-branch",
    title: "第一枝柘木",
    locationId: "fajiu-mountain",
    activeCharacterIds: ["jingwei", "fajiu-keeper", "east-sea-envoy"],
    event: "精卫衔起第一枝柘木，东海潮声已经在远处回应；山守提醒她，山材和誓愿都不能无代价地消耗。",
    suggestedGoals: [
      "以精卫之身让东海第一次承认女娃之名",
      "在不耗尽发鸠山的前提下推进填海誓愿",
      "召集山、河、旅人与神族见证精卫衔木石的意义",
    ],
  },
};

export const odysseyWorldPack: WorldPack = {
  schemaVersion: "world-pack-v1",
  worldPackId: ODYSSEY_WORLD_PACK_ID,
  version: 1,
  visibility: "curated",
  sourceType: "narrative",
  worldTemplate: "mythic_exploration",
  title: "The Odyssey: The Cyclops' Cave",
  language: "en",
  premise:
    "After leaving Troy, Odysseus and a small crew enter the cave of Polyphemus, expecting guest-right but finding a giant who seals the entrance with a boulder. The chapter turns on cunning, timing, crew trust, divine law, and the cost of naming yourself.",
  timeAnchor:
    "The Odyssey, Book IX: Odysseus recounts how he and his men were trapped in Polyphemus' cave, used wine and the name Noman, blinded the Cyclops, and escaped beneath the sheep.",
  sourceAttribution: {
    label: "Homer, The Odyssey Book IX, Samuel Butler public-domain translation",
    rightsBasis: "public-domain",
  },
  canonFacts: [
    {
      id: "fact-cyclops-island",
      statement: "Odysseus reaches the land of the Cyclopes during his voyage home after Troy.",
      tags: ["voyage", "setting"],
    },
    {
      id: "fact-cave-supplies",
      statement: "Polyphemus' cave contains cheeses, lambs, kids, pens, and stores that tempt the crew to take supplies and leave.",
      tags: ["location", "resource"],
    },
    {
      id: "fact-guest-right-tested",
      statement: "Odysseus asks for guest-gifts under the protection of Zeus, but Polyphemus rejects the law of hospitality.",
      tags: ["xenia", "divine-law"],
    },
    {
      id: "fact-boulder-seals-cave",
      statement: "Polyphemus rolls a massive stone across the cave mouth, trapping Odysseus and his men inside.",
      tags: ["trap", "boundary"],
    },
    {
      id: "fact-polyphemus-eats-men",
      statement: "Polyphemus kills and eats members of the crew, making delay dangerous and trust fragile.",
      tags: ["danger", "loss"],
    },
    {
      id: "fact-cannot-move-stone",
      statement: "The crew cannot simply kill Polyphemus at first, because only he can move the boulder from the cave entrance.",
      tags: ["constraint", "escape"],
    },
    {
      id: "fact-olive-stake",
      statement: "Odysseus prepares a sharpened olive-wood stake and hides it for the moment when Polyphemus sleeps.",
      tags: ["tool", "planning"],
    },
    {
      id: "fact-maronaean-wine",
      statement: "Odysseus carries strong wine from Maron, which can intoxicate Polyphemus and create an opening.",
      tags: ["resource", "trick"],
    },
    {
      id: "fact-noman-name",
      statement: "Odysseus tells Polyphemus that his name is Noman, so the wounded Cyclops later says Noman is hurting him.",
      tags: ["deception", "name"],
    },
    {
      id: "fact-cyclops-neighbors",
      statement: "Neighboring Cyclopes hear Polyphemus cry out, but the Noman trick makes them misunderstand the threat.",
      tags: ["witness", "misdirection"],
    },
    {
      id: "fact-sheep-escape",
      statement: "Odysseus and his men escape by clinging beneath Polyphemus' sheep as they leave the cave.",
      tags: ["escape", "timing"],
    },
    {
      id: "fact-old-ram",
      statement: "Polyphemus' old ram becomes the most important animal in the escape because Odysseus hides beneath it.",
      tags: ["animal", "escape"],
    },
    {
      id: "fact-taunt-reveals-name",
      statement: "After escaping, Odysseus reveals his true name to Polyphemus, gaining glory but inviting a curse.",
      tags: ["glory", "cost"],
    },
    {
      id: "fact-poseidon-curse",
      statement: "Polyphemus prays to Poseidon, his father, asking that Odysseus suffer on the voyage home.",
      tags: ["divine-pressure", "future-cost"],
    },
    {
      id: "fact-crew-warning",
      statement: "The crew urges Odysseus not to keep taunting Polyphemus from the ship, because stones can still reach them.",
      tags: ["crew", "prudence"],
    },
    {
      id: "fact-custom-action-boundary",
      statement: "Player actions must remain within archaic epic means: speech, timing, tools, ritual appeals, deception, courage, and seamanship rather than modern technology.",
      tags: ["rule", "player"],
    },
  ],
  rules: [
    {
      id: "rule-public-domain-source",
      description: "Core events must remain anchored in The Odyssey Book IX: cave entry, hospitality failure, boulder trap, wine, Noman, blinding, sheep escape, and Poseidon's curse.",
      severity: "hard",
    },
    {
      id: "rule-epic-boundary",
      description: "No modern weapons, maps, engines, radios, medicine, or knowledge outside the archaic epic world.",
      severity: "hard",
    },
    {
      id: "rule-boulder-constraint",
      description: "The stone blocking the cave cannot be casually moved by the crew; escape must solve the boulder, Polyphemus, or the sheepfold timing.",
      severity: "hard",
    },
    {
      id: "rule-cunning-has-cost",
      description: "Cunning can save lives, but public glory, divine law, and crew trust create consequences that carry into later turns.",
      severity: "soft",
    },
  ],
  locations: [
    {
      id: "cyclops-shore",
      name: "Cyclops shore",
      description: "The rocky landing place where Odysseus' ship waits within reach of thrown stones, surf, and frightened crew.",
      connectedLocationIds: ["polyphemus-cave", "sheepfold-threshold"],
    },
    {
      id: "polyphemus-cave",
      name: "Polyphemus' cave",
      description: "A deep cave of cheeses, pens, lambs, kids, smoke, and a stone door too large for mortal sailors to move.",
      connectedLocationIds: ["cyclops-shore", "sheepfold-threshold"],
    },
    {
      id: "sheepfold-threshold",
      name: "Sheepfold threshold",
      description: "The cave mouth and animal pens where Polyphemus counts his flock by touch and escape depends on timing.",
      connectedLocationIds: ["polyphemus-cave", "cyclops-shore"],
    },
  ],
  characters: [
    {
      id: "odysseus",
      name: "Odysseus",
      playable: true,
      identity: "King of Ithaca, veteran of Troy, and strategist trying to bring his crew home.",
      personality: ["cunning", "bold", "hungry for glory"],
      goals: ["save surviving crew members", "turn the cave trap into an escape plan", "win glory without losing the voyage home"],
      capabilities: ["deception", "leadership", "timing plans", "appeals to guest-right", "seamanship"],
      limitations: ["cannot move the boulder alone", "pride can override prudence", "crew trust weakens with each death"],
      knownFactIds: [
        "fact-cave-supplies",
        "fact-guest-right-tested",
        "fact-boulder-seals-cave",
        "fact-cannot-move-stone",
        "fact-maronaean-wine",
      ],
      unknownFactIds: ["fact-poseidon-curse", "fact-old-ram"],
      hiddenAgenda: "He wants survival, but also wants the deed remembered under his true name.",
    },
    {
      id: "achaean-sailor",
      name: "Achaean Sailor",
      playable: true,
      identity: "One of Odysseus' surviving companions, caught between obedience, fear, and practical escape.",
      personality: ["loyal", "frightened", "practical"],
      goals: ["get back to the ship alive", "keep the crew from wasting chances", "make Odysseus hear the cost of pride"],
      capabilities: ["rowing", "hauling supplies", "holding formation", "watching the Cyclops' habits"],
      limitations: ["no authority over Odysseus", "physically outmatched by Polyphemus", "panic spreads quickly among the men"],
      knownFactIds: ["fact-boulder-seals-cave", "fact-polyphemus-eats-men", "fact-cannot-move-stone", "fact-crew-warning"],
      unknownFactIds: ["fact-noman-name", "fact-poseidon-curse"],
      hiddenAgenda: "He may support cunning, but he will resist choices that trade lives for fame.",
    },
    {
      id: "noman",
      name: "Noman",
      playable: true,
      identity: "The false name and tactical mask Odysseus uses to turn language against Polyphemus.",
      personality: ["slippery", "patient", "built for misdirection"],
      goals: ["make the Cyclops misunderstand the attack", "protect Odysseus until escape is possible", "keep the trick from collapsing too soon"],
      capabilities: ["misnaming", "misdirection", "turning witness speech against itself"],
      limitations: ["exists only while others believe the name", "cannot carry glory after the escape"],
      knownFactIds: ["fact-noman-name", "fact-cyclops-neighbors", "fact-olive-stake"],
      unknownFactIds: ["fact-taunt-reveals-name", "fact-poseidon-curse"],
      hiddenAgenda: "The mask wants the plan to survive even if Odysseus' pride wants to discard it.",
    },
    {
      id: "ship-lookout",
      name: "Ship Lookout",
      playable: true,
      identity: "A sailor left near the ship, watching the cave path, surf, and danger from the shore.",
      personality: ["watchful", "nervous", "fast to warn"],
      goals: ["keep the ship ready", "warn the cave party before the sea route closes", "prevent a late taunt from killing everyone"],
      capabilities: ["shore watch", "crew signals", "reading surf and thrown-stone range"],
      limitations: ["cannot enter the sealed cave", "knows only what reaches the shore"],
      knownFactIds: ["fact-cyclops-island", "fact-crew-warning", "fact-taunt-reveals-name"],
      unknownFactIds: ["fact-noman-name", "fact-old-ram"],
      hiddenAgenda: "He values the living crew over any heroic story told later.",
    },
    {
      id: "polyphemus",
      name: "Polyphemus",
      playable: false,
      identity: "A Cyclops shepherd, son of Poseidon, who traps Odysseus' men in his cave.",
      personality: ["brutal", "isolated", "contemptuous of guest-right"],
      goals: ["eat the intruders", "protect his cave and flock", "punish the man who blinds him"],
      capabilities: ["giant strength", "moving the boulder", "counting sheep by touch", "calling neighboring Cyclopes"],
      limitations: ["vulnerable to intoxication", "can be deceived by names", "blindness turns his strength clumsy"],
      knownFactIds: ["fact-boulder-seals-cave", "fact-polyphemus-eats-men", "fact-noman-name", "fact-old-ram"],
      unknownFactIds: ["fact-taunt-reveals-name"],
      hiddenAgenda: "He will invoke Poseidon if his private humiliation becomes public.",
    },
    {
      id: "old-ram",
      name: "Old Ram",
      playable: false,
      identity: "The largest ram in Polyphemus' flock, later carrying Odysseus beneath its belly.",
      personality: ["slow", "trusted by Polyphemus", "bound to animal habit"],
      goals: ["leave the cave with the flock", "avoid panic at the threshold"],
      capabilities: ["passes Polyphemus' touch", "moves through the sheepfold", "can hide a man beneath its wool"],
      limitations: ["cannot understand the full plan", "timing depends on flock movement"],
      knownFactIds: ["fact-sheep-escape", "fact-old-ram"],
      unknownFactIds: ["fact-poseidon-curse"],
      hiddenAgenda: "Its ordinary habit can defeat a monster more quietly than heroic force.",
    },
    {
      id: "cyclops-neighbors",
      name: "Cyclops Neighbors",
      playable: false,
      identity: "Other Cyclopes close enough to hear Polyphemus cry from the cave.",
      personality: ["suspicious", "literal-minded", "unwilling to intervene without clear cause"],
      goals: ["avoid needless trouble", "understand whether Polyphemus is attacked by force or by divine sickness"],
      capabilities: ["responding to cries", "spreading Cyclops judgment", "blocking outside escape if convinced"],
      limitations: ["misled by the name Noman", "slow to organize collectively"],
      knownFactIds: ["fact-cyclops-neighbors", "fact-noman-name"],
      unknownFactIds: ["fact-olive-stake", "fact-sheep-escape"],
      hiddenAgenda: "They prefer the cave's trouble to remain Polyphemus' private problem.",
    },
    {
      id: "poseidon",
      name: "Poseidon",
      playable: false,
      identity: "Sea god and father of Polyphemus, able to make the voyage home bitter.",
      personality: ["distant", "vengeful", "bound to honor his son's prayer"],
      goals: ["answer Polyphemus' curse", "make Odysseus pay for revealed violence and pride"],
      capabilities: ["sea storms", "long-range divine pressure", "turning victory into future cost"],
      limitations: ["not directly present in the cave", "the curse requires invocation and a name"],
      knownFactIds: ["fact-poseidon-curse", "fact-taunt-reveals-name"],
      unknownFactIds: ["fact-noman-name"],
      hiddenAgenda: "He turns the choice to claim glory into a longer trial at sea.",
    },
    {
      id: "zeus-xenios",
      name: "Zeus Xenios",
      playable: false,
      identity: "The divine pressure behind guest-right and the moral claim Odysseus invokes.",
      personality: ["formal", "judging", "not easily reduced to immediate rescue"],
      goals: ["keep the law of hospitality meaningful", "mark Polyphemus' violation without erasing mortal consequences"],
      capabilities: ["religious legitimacy", "omens", "moral framing"],
      limitations: ["does not simply open the cave", "justice may arrive through human cunning"],
      knownFactIds: ["fact-guest-right-tested", "fact-polyphemus-eats-men"],
      unknownFactIds: ["fact-taunt-reveals-name"],
      hiddenAgenda: "Guest-right can justify resistance, but not every reckless choice afterward.",
    },
    {
      id: "maronaean-wine",
      name: "Maronaean Wine",
      playable: false,
      identity: "The strong wine Odysseus carries from Maron, potent enough to cloud the Cyclops' judgment.",
      personality: ["sweet", "dangerous", "revealing"],
      goals: ["open a window for deception", "turn appetite into vulnerability"],
      capabilities: ["intoxicating Polyphemus", "slowing reaction", "making speech loose"],
      limitations: ["finite supply", "useless if offered at the wrong moment"],
      knownFactIds: ["fact-maronaean-wine", "fact-noman-name"],
      unknownFactIds: ["fact-poseidon-curse"],
      hiddenAgenda: "It can save the crew only if paired with patience and a believable story.",
    },
  ],
  relationships: [
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "achaean-sailor",
      kind: "captain-and-crew",
      affinity: 2,
      tension: 3,
      publicContext: "The sailor depends on Odysseus' cunning but fears his appetite for glory will cost more lives.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "polyphemus",
      kind: "guest-right-violated",
      affinity: -5,
      tension: 5,
      publicContext: "Odysseus comes as a guest and becomes prey in Polyphemus' cave.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "noman",
      kind: "name-mask",
      affinity: 3,
      tension: 2,
      publicContext: "Noman protects Odysseus' plan but conflicts with his desire to claim the deed.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "maronaean-wine",
      kind: "tool-of-cunning",
      affinity: 3,
      tension: 1,
      publicContext: "The wine is a precious tool, not a solution unless the timing is right.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "old-ram",
      kind: "escape-carrier",
      affinity: 1,
      tension: 1,
      publicContext: "The old ram can carry Odysseus through the threshold if the plan remains quiet.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "poseidon",
      kind: "future-divine-enmity",
      affinity: -4,
      tension: 4,
      publicContext: "Odysseus does not face Poseidon in the cave, but revealing his name can awaken the sea god's anger.",
    },
    {
      sourceCharacterId: "polyphemus",
      targetCharacterId: "poseidon",
      kind: "father-and-son",
      affinity: 3,
      tension: 1,
      publicContext: "Polyphemus can call on Poseidon after being wounded and named.",
    },
    {
      sourceCharacterId: "polyphemus",
      targetCharacterId: "old-ram",
      kind: "shepherd-and-flock",
      affinity: 2,
      tension: 1,
      publicContext: "Polyphemus trusts the ram as part of his daily flock rhythm.",
    },
    {
      sourceCharacterId: "polyphemus",
      targetCharacterId: "cyclops-neighbors",
      kind: "isolated-neighbors",
      affinity: 0,
      tension: 2,
      publicContext: "The neighbors hear him but are unlikely to help unless the threat is clear.",
    },
    {
      sourceCharacterId: "noman",
      targetCharacterId: "cyclops-neighbors",
      kind: "misdirection",
      affinity: 0,
      tension: 3,
      publicContext: "The false name turns the neighbors' hearing into confusion.",
    },
    {
      sourceCharacterId: "achaean-sailor",
      targetCharacterId: "ship-lookout",
      kind: "crew-survival",
      affinity: 3,
      tension: 1,
      publicContext: "Both care more about returning to the ship alive than winning a famous boast.",
    },
    {
      sourceCharacterId: "odysseus",
      targetCharacterId: "zeus-xenios",
      kind: "appeal-to-guest-right",
      affinity: 1,
      tension: 2,
      publicContext: "Odysseus invokes guest-right, but divine law gives legitimacy rather than instant rescue.",
    },
    {
      sourceCharacterId: "polyphemus",
      targetCharacterId: "zeus-xenios",
      kind: "contempt-for-hospitality",
      affinity: -3,
      tension: 4,
      publicContext: "Polyphemus rejects the guest-law that Odysseus uses to frame the conflict.",
    },
  ],
  factions: [
    {
      id: "faction-ithacan-crew",
      name: "Ithacan crew",
      role: "survival coalition",
      publicGoal: "Escape the cave and return to the ship with as many men as possible.",
      hiddenPressure: "Crew trust drops whenever Odysseus chooses fame over caution.",
      influence: 0.76,
      memberCharacterIds: ["odysseus", "achaean-sailor", "ship-lookout", "noman"],
    },
    {
      id: "faction-cyclops-household",
      name: "Cyclops cave order",
      role: "monster territory",
      publicGoal: "Keep intruders trapped and preserve Polyphemus' flock and cave.",
      hiddenPressure: "Blindness turns daily habits into vulnerabilities.",
      influence: 0.86,
      memberCharacterIds: ["polyphemus", "old-ram", "cyclops-neighbors"],
    },
    {
      id: "faction-divine-law",
      name: "Guest-right and divine witness",
      role: "moral pressure",
      publicGoal: "Make the violation of hospitality meaningful.",
      hiddenPressure: "Justice does not prevent later punishment for pride.",
      influence: 0.64,
      memberCharacterIds: ["zeus-xenios", "poseidon"],
    },
    {
      id: "faction-sea-homeward",
      name: "Homeward sea path",
      role: "future consequence",
      publicGoal: "Carry the ship away from Cyclops land toward Ithaca.",
      hiddenPressure: "Poseidon's curse can turn a local escape into a long wandering.",
      influence: 0.68,
      memberCharacterIds: ["ship-lookout", "poseidon"],
    },
  ],
  eventSeeds: [
    {
      id: "event-cave-entry",
      turnCreated: 0,
      dueTurn: 1,
      source: "world",
      visibility: "public",
      severity: 0.44,
      status: "scheduled",
      description: "The cave stores tempt the crew to take supplies and leave before the owner returns.",
      linkedCharacterIds: ["odysseus", "achaean-sailor"],
      linkedFactionIds: ["faction-ithacan-crew"],
    },
    {
      id: "event-boulder-seal",
      turnCreated: 0,
      dueTurn: 1,
      source: "npc",
      visibility: "public",
      severity: 0.65,
      status: "scheduled",
      description: "Polyphemus rolls the huge stone across the cave mouth and traps the men inside.",
      linkedCharacterIds: ["polyphemus", "odysseus", "achaean-sailor"],
      linkedFactionIds: ["faction-cyclops-household", "faction-ithacan-crew"],
    },
    {
      id: "event-first-deaths",
      turnCreated: 0,
      dueTurn: 2,
      source: "world",
      visibility: "public",
      severity: 0.78,
      status: "scheduled",
      description: "Polyphemus eats members of the crew, forcing the survivors to choose patience or desperate force.",
      linkedCharacterIds: ["polyphemus", "odysseus", "achaean-sailor"],
      linkedFactionIds: ["faction-cyclops-household", "faction-ithacan-crew"],
    },
    {
      id: "event-wine-opening",
      turnCreated: 0,
      dueTurn: 2,
      source: "player",
      visibility: "private",
      severity: 0.52,
      status: "scheduled",
      description: "The Maronaean wine can turn Polyphemus' appetite into a moment of vulnerability.",
      linkedCharacterIds: ["odysseus", "maronaean-wine", "polyphemus"],
      linkedFactionIds: ["faction-ithacan-crew"],
    },
    {
      id: "event-noman-cry",
      turnCreated: 0,
      dueTurn: 3,
      source: "player",
      visibility: "public",
      severity: 0.56,
      status: "scheduled",
      description: "If the false name holds, Polyphemus' cry will mislead the neighboring Cyclopes.",
      linkedCharacterIds: ["noman", "polyphemus", "cyclops-neighbors"],
      linkedFactionIds: ["faction-cyclops-household", "faction-ithacan-crew"],
    },
    {
      id: "event-sheep-counting",
      turnCreated: 0,
      dueTurn: 4,
      source: "world",
      visibility: "public",
      severity: 0.62,
      status: "scheduled",
      description: "The sheep must pass under Polyphemus' hands at the threshold, making timing and concealment decisive.",
      linkedCharacterIds: ["old-ram", "polyphemus", "odysseus"],
      linkedFactionIds: ["faction-cyclops-household", "faction-ithacan-crew"],
    },
    {
      id: "event-name-temptation",
      turnCreated: 0,
      dueTurn: 5,
      source: "world",
      visibility: "rumor",
      severity: 0.7,
      status: "scheduled",
      description: "Once the ship clears the shore, the desire to reveal the true name fights against the crew's warning.",
      linkedCharacterIds: ["odysseus", "ship-lookout", "poseidon"],
      linkedFactionIds: ["faction-ithacan-crew", "faction-sea-homeward"],
    },
  ],
  pressureDefaults: {
    ritualOrder: 38,
    householdOrder: 24,
    publicFace: 52,
    hiddenResentment: 40,
    authorityLegitimacy: 56,
    informationClarity: 35,
  },
  openingScenario: {
    id: "opening-cave-sealed",
    title: "The stone at the cave mouth",
    locationId: "polyphemus-cave",
    activeCharacterIds: ["odysseus", "achaean-sailor", "polyphemus"],
    event: "Polyphemus has returned, driven in his flock, and rolled the massive stone across the cave mouth. Odysseus must decide whether to press guest-right, hide intentions, or start shaping an escape before more men die.",
    suggestedGoals: [
      "escape Polyphemus' cave with the surviving crew",
      "use cunning without letting Odysseus' pride destroy the voyage home",
      "turn the cave's own flock, wine, and names into a path back to the ship",
    ],
  },
};

const curatedWorldPacks = new Map<string, WorldPack>([
  [redChamberWorldPack.worldPackId, redChamberWorldPack],
  [shanhaijingWorldPack.worldPackId, shanhaijingWorldPack],
  [odysseyWorldPack.worldPackId, odysseyWorldPack],
]);

export function getCuratedWorldPack(worldPackId: string): WorldPack | undefined {
  return curatedWorldPacks.get(worldPackId);
}

export function listCuratedWorldPacks(): WorldPack[] {
  return [...curatedWorldPacks.values()];
}
